
// We make a fake module just to namespace all native godot calls with GD.
#import "Math";
#import "Basic";
#import "String";

#load "generated/gdextension_interface.jai";
#load "generated/builtin.jai";
#load "generated/classes.jai";
#load "generated/other.jai";



#load "src/strings.jai";
#load "src/variant.jai";
#load "src/helpers.jai";
#load "src/runtime.jai";
#load "src/registration.jai";

#load "common.jai";